version: "3.0"

services:
  server_node_js:
    container_name: server_node_js
    volumes:
      - ./nodejs:/server/nodejs
      - /server/nodejs/node_modules
  
    image: node:20

    working_dir: /server/nodejs
  
    ports:
      - 80:3000

    depends_on:
      - db
    
    command: ["npm", "start"]


  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/saved:/var/lib/mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - 3000:3306

